packages:
  - docs
  - packages/*
catalog:
  '@vueuse/core': ^13.0.0
  element-plus: ^2.9.7
  vue: ^3.5.13
overrides:
  '@shikijs/core': ^3.2.1
  '@shikijs/markdown-it': ^3.2.1
  '@shikijs/rehype': ^3.2.1
  '@shikijs/transformers': ^3.2.1
  '@shikijs/types': ^3.2.1
  esbuild: ^0.25.2
  shiki: ^3.2.1
  vite: ^6.2.4
onlyBuiltDependencies:
  - esbuild
  - vue-demi
peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - '@types/react'
    - react
    - react-dom
