packages:
  - docs
  - packages/*
overrides:
  esbuild: ^0.27.2
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - '@types/react'
    - react
    - react-dom
