packages:
  - docs
  - packages/*
overrides:
  vite: ^8.0.0-beta.12
  esbuild: ^0.27.2
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - '@types/react'
    - react
    - react-dom
